'use strict';

import { OptionsInterface } from "../../typings/seeders";

let options:OptionsInterface = {};
if (process.env.NODE_ENV === 'production') {
  options.schema = process.env.SCHEMA;  
}

module.exports = {
  up: async (queryInterface:any, Sequelize:any) => {
    options.tableName = 'Pets';
    
    const petsData = [
      {
        name: 'Buddy',
        species: 'Dog',
        breed: 'Labrador Retriever Mix',
        age: 3,
        gender: 'Male',
        size: 'Large',
        color: 'Golden',
        fee: 75.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Buddy is a friendly and energetic lab mix who loves playing fetch and going for walks. He's great with kids and other dogs. House trained and knows basic commands.",
        userId: 4,
        shelterId: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Luna',
        species: 'Cat',
        breed: 'Domestic Shorthair',
        age: 2,
        gender: 'Female',
        size: 'Medium',
        color: 'Gray and White',
        fee: 50.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Luna is a sweet and gentle cat who loves to cuddle. She's litter trained and gets along well with other cats. Perfect for a quiet home.",
        userId: 4,
        shelterId: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Max',
        species: 'Dog',
        breed: 'German Shepherd Mix',
        age: 4,
        gender: 'Male',
        size: 'Large',
        color: 'Black and Tan',
        fee: 75.00,
        status: 'protective custody',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Max is a loyal and intelligent dog currently in protective custody pending legal resolution. He's protective but gentle, and loves outdoor activities.",
        userId: 4,
        shelterId: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Patches',
        species: 'Cat',
        breed: 'Tabby Mix',
        age: 4,
        gender: 'Female',
        size: 'Medium',
        color: 'Orange Tabby',
        fee: 50.00,
        status: 'adopted',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: 'Patches was a friendly tabby who loved attention and treats. She found her forever home and is now living happily with her new family.',
        userId: 4,
        shelterId: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Charlie',
        species: 'Dog',
        breed: 'Golden Retriever Mix',
        age: 2,
        gender: 'Male',
        size: 'Large',
        color: 'Golden',
        fee: 150.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Charlie is a beautiful golden mix with a gentle temperament. He's fully vaccinated, neutered, and loves swimming. Perfect family dog.",
        userId: 2,
        shelterId: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Princess',
        species: 'Cat',
        breed: 'Persian Mix',
        age: 3,
        gender: 'Female',
        size: 'Medium',
        color: 'White',
        fee: 125.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Princess is a long-haired beauty who loves to be pampered. She's spayed, vaccinated, and tested for FIV/FeLV. Prefers to be the only cat.",
        userId: 2,
        shelterId: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Ranger',
        species: 'Dog',
        breed: 'Border Collie Mix',
        age: 1,
        gender: 'Male',
        size: 'Medium',
        color: 'Black and White',
        fee: 150.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: 'Ranger is a highly intelligent and energetic young dog. He needs an active family and would excel at agility or obedience training.',
        userId: 2,
        shelterId: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Daisy',
        species: 'Dog',
        breed: 'Cocker Spaniel Mix',
        age: 4,
        gender: 'Female',
        size: 'Medium',
        color: 'Golden',
        fee: 100.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Daisy is a sweet and gentle dog who loves children. She's house trained, spayed, and has the most beautiful coat. Perfect lap dog.",
        userId: 3,
        shelterId: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Oliver',
        species: 'Cat',
        breed: 'Tuxedo',
        age: 2,
        gender: 'Male',
        size: 'Medium',
        color: 'Black and White',
        fee: 75.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Oliver is a handsome tuxedo cat who thinks he's quite distinguished. He loves to sit properly and observe his domain from high perches.",
        userId: 3,
        shelterId: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Ruby',
        species: 'Dog',
        breed: 'Dachshund Mix',
        age: 3,
        gender: 'Female',
        size: 'Small',
        color: 'Red',
        fee: 100.00,
        status: 'adopted',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: 'Ruby was a little sausage dog with a big heart. She found her perfect home with a senior who loves to have her as a lap companion.',
        userId: 3,
        shelterId: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Zeus',
        species: 'Dog',
        breed: 'Great Dane Mix',
        age: 3,
        gender: 'Male',
        size: 'Large',
        color: 'Blue',
        fee: 125.00,
        status: 'available',
        expireDate: '2025-07-03T07:18:16.077Z',
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Zeus is a majestic Great Dane mix who thinks he's a lap dog. He's gentle with children and loves to lean against his favorite people for cuddles.",
        userId: 1,
        shelterId: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Nala',
        species: 'Cat',
        breed: 'Bengal Mix',
        age: 2,
        gender: 'Female',
        size: 'Medium',
        color: 'Brown Spotted',
        fee: 100.00,
        status: 'available',
        expireDate: '2025-06-24T07:18:16.077Z',
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Nala is a striking Bengal mix with beautiful markings. She's very active and intelligent, loves to climb and would enjoy puzzle toys.",
        userId: 1,
        shelterId: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Rusty',
        species: 'Dog',
        breed: 'Cattle Dog Mix',
        age: 3,
        gender: 'Male',
        size: 'Medium',
        color: 'Red Heeler',
        fee: 250.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Rusty is a hardworking cattle dog mix who's fully vetted and trained. He knows basic commands and is great with kids. Looking for an active family who can give him a job to do.",
        userId: 5,
        shelterId: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Dolly',
        species: 'Dog',
        breed: 'Beagle Hound Mix',
        age: 4,
        gender: 'Female',
        size: 'Medium',
        color: 'Tri-color',
        fee: 250.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Dolly is a sweet hound mix with a gentle nature. She's fully vaccinated, spayed, and loves going on walks. Perfect for a family looking for a calm, loving companion.",
        userId: 5,
        shelterId: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Tucker',
        species: 'Dog',
        breed: 'Lab Pit Mix',
        age: 2,
        gender: 'Male',
        size: 'Large',
        color: 'Brindle',
        fee: 250.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Tucker is a young, energetic mix who loves to play fetch. He's fully vetted, neutered, and has received training. Great with kids and other dogs.",
        userId: 5,
        shelterId: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Willow',
        species: 'Dog',
        breed: 'Australian Shepherd Mix',
        age: 3,
        gender: 'Female',
        size: 'Medium',
        color: 'Red Merle',
        fee: 200.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Willow was rescued as a stray and rehabilitated. She's now ready for adoption and loves outdoor activities. Great with other dogs and children.",
        userId: 6,
        shelterId: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Forest',
        species: 'Cat',
        breed: 'Maine Coon Mix',
        age: 4,
        gender: 'Male',
        size: 'Large',
        color: 'Brown Tabby',
        fee: 150.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: 'Forest is a large, gentle cat who was found injured and nursed back to health. He loves nature and would do well in a home with outdoor access.',
        userId: 6,
        shelterId: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Austin',
        species: 'Dog',
        breed: 'Labrador Mix',
        age: 3,
        gender: 'Male',
        size: 'Large',
        color: 'Chocolate',
        fee: 175.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Austin is a friendly lab mix who loves everyone he meets. He's great with kids, other dogs, and even cats. Perfect family dog who loves to play fetch.",
        userId: 2,
        shelterId: 7,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Bluebonnet',
        species: 'Cat',
        breed: 'Russian Blue Mix',
        age: 2,
        gender: 'Female',
        size: 'Medium',
        color: 'Blue Gray',
        fee: 125.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Bluebonnet is a beautiful blue-gray cat with green eyes. She's calm and affectionate, perfect for someone looking for a gentle lap cat.",
        userId: 4,
        shelterId: 7,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Mittens',
        species: 'Cat',
        breed: 'Calico',
        age: 3,
        gender: 'Female',
        size: 'Medium',
        color: 'Calico',
        fee: 0.00,
        status: 'missing',
        expireDate: null,
        lastSeenLocation: 'Hobby Lobby parking lot',
        lastSeenDate: '2025-06-05T07:18:16.077Z',
        description: "Mittens is a beautiful calico who went missing from her home. She's friendly and microchipped. Family desperately seeking her return. Please contact owner if found.",
        userId: 6,
        shelterId: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Shadow',
        species: 'Dog',
        breed: 'German Shepherd',
        age: 5,
        gender: 'Male',
        size: 'Large',
        color: 'Black and Tan',
        fee: 0.00,
        status: 'missing',
        expireDate: null,
        lastSeenLocation: 'Bow Lane',
        lastSeenDate: '2025-06-12T07:18:16.077Z',
        description: "Shadow is a large German Shepherd who escaped from his yard during a storm. He's friendly but may be scared. Please approach carefully and contact owner immediately if seen.",
        userId: 5,
        shelterId: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Lucky',
        species: 'Dog',
        breed: 'Beagle Mix',
        age: 6,
        gender: 'Male',
        size: 'Medium',
        color: 'Tri-color',
        fee: 0.00,
        status: 'found',
        expireDate: null,
        lastSeenLocation: 'Methodist Encampment',
        lastSeenDate: '2025-06-19T07:18:16.077Z',
        description: 'Lucky was missing for 3 days but has been safely reunited with his family! Thanks to everyone who helped search and shared his information.',
        userId: 1,
        shelterId: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Bella',
        species: 'Cat',
        breed: 'Domestic Shorthair',
        age: 2,
        gender: 'Female',
        size: 'Medium',
        color: 'Gray',
        fee: 0.00,
        status: 'found',
        expireDate: null,
        lastSeenLocation: 'Walmart pet section',
        lastSeenDate: "2025-06-03T07:18:16.077Z",
        description: "Bella was found safe after being missing for a week! She's back home with her family and doing well. Thank you to everyone who helped look for her.",
        userId: 4,
        shelterId: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Tex',
        species: 'Dog',
        breed: 'Blue Heeler Mix',
        age: 5,
        gender: 'Male',
        size: 'Medium',
        color: 'Blue Speckled',
        fee: 75.00,
        status: 'available',
        expireDate: '2025-06-30T07:18:16.077Z',
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Tex is a true Texas cowboy dog who loves wide open spaces. He's loyal, hardworking, and would be perfect for someone with land or who loves outdoor activities.",
        userId: 4,
        shelterId: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Peaches',
        species: 'Cat',
        breed: 'Orange Persian Mix',
        age: 3,
        gender: 'Female',
        size: 'Medium',
        color: 'Orange',
        fee: 50.00,
        status: 'available',
        expireDate: '2025-06-28T07:18:16.077Z',
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Peaches is a fluffy orange beauty who loves to be groomed and pampered. She's calm and affectionate, perfect for someone who enjoys caring for a long-haired cat.",
        userId: 4,
        shelterId: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Cowboy',
        species: 'Dog',
        breed: 'Cattle Dog Mix',
        age: 2,
        gender: 'Male',
        size: 'Medium',
        color: 'Red Heeler',
        fee: 150.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Cowboy is a hardworking cattle dog who needs a job to do. He's great for active families or working ranches. Very loyal and intelligent.",
        userId: 2,
        shelterId: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Honey',
        species: 'Dog',
        breed: 'Golden Retriever',
        age: 7,
        gender: 'Female',
        size: 'Large',
        color: 'Golden',
        fee: 100.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Honey is a senior golden who still has lots of love to give. She's calm, well-trained, and would be perfect for someone looking for a gentle companion.",
        userId: 3,
        shelterId: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Storm',
        species: 'Cat',
        breed: 'Gray Tabby',
        age: 1,
        gender: 'Male',
        size: 'Medium',
        color: 'Silver Tabby',
        fee: 75.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: 'Storm is a young gray tabby with lots of energy. He loves to play and would do well in a home with other young cats or children to keep him entertained.',
        userId: 3,
        shelterId: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Maverick',
        species: 'Dog',
        breed: 'Husky Mix',
        age: 2,
        gender: 'Male',
        size: 'Large',
        color: 'Gray and White',
        fee: 250.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Maverick is a beautiful husky mix with striking blue eyes. He's energetic and needs lots of exercise. Perfect for an active family who loves outdoor adventures. Fully vetted and trained.",
        userId: 5,
        shelterId: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Jasper',
        species: 'Cat',
        breed: 'Maine Coon',
        age: 3,
        gender: 'Male',
        size: 'Large',
        color: 'Silver Tabby',
        fee: 150.00,
        status: 'available',
        expireDate: null,
        lastSeenLocation: null,
        lastSeenDate: null,
        description: "Jasper is a magnificent Maine Coon with a gentle giant personality. He's great with kids and other pets, and loves to be brushed. Rescued and rehabilitated.",
        userId: 6,
        shelterId: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ];

    return queryInterface.bulkInsert(
      options,
      petsData,
      {
        ignoreDuplicates: true
      }
    );
  },

  down: async (queryInterface:any, Sequelize:any) => {
    options.tableName = 'Pets';
    const Op = Sequelize.Op;
    return queryInterface.bulkDelete(options, {
      name: { 
        [Op.in]: [
          'Buddy', 'Luna', 'Max', 'Patches', 'Charlie', 'Princess', 'Ranger', 'Daisy', 
          'Oliver', 'Ruby', 'Zeus', 'Nala', 'Rusty', 'Dolly', 'Tucker', 'Willow', 
          'Forest', 'Austin', 'Bluebonnet', 'Mittens', 'Shadow', 'Lucky', 'Bella', 
          'Tex', 'Peaches', 'Cowboy', 'Honey', 'Storm', 'Maverick', 'Jasper'
        ] 
      }
    }, {});
  }
};
