export interface IPet {
    id: number,
    name: string,
    species: string,
    breed: string,
    age: string,
    gender: string,
    size: string,
    fee: number,
    status: string,
    description: string,
    userId: number,
    shelterId: number,
    expireDate: string,
    lastSeenDate: string,
    lastSeenLocation: string,
    color: string,
}